Repository Wall-Go/WallGo, pull requests merged in 2024-11, with the labels that each got.

#340 Tidy xSM folder
  Models/SingletStandardModel_Z2/MatrixElements/MatrixElements_QCD_BenoitBenchmark.txt
  Models/SingletStandardModel_Z2/MatrixElements/MatrixElements_QCD_BeyondLL.txt
  Models/SingletStandardModel_Z2/README.rst
  Models/SingletStandardModel_Z2/SingletStandardModel_Z2_Simple.py
Labels: tidy

#347 pre-v1.0.0 tweaks
  CHANGELOG.rst
  Developer/createThermalFunctionTables.py
  README.md
  src/WallGo/PotentialTools/effectivePotentialNoResum.py
  src/WallGo/boltzmann.py
  src/WallGo/collisionArray.py
  src/WallGo/effectivePotential.py
  src/WallGo/equationOfMotion.py
  src/WallGo/freeEnergy.py
  src/WallGo/grid.py
  src/WallGo/hydrodynamics.py
  src/WallGo/manager.py
  src/WallGo/particle.py
  src/WallGo/results.py
Labels: documentation

#350 Fixing broken PyPI publishing
  .github/workflows/main.yml
  .github/workflows/publish.yml
  .github/workflows/tests.yml
  pyproject.toml
  tests/TestData/N11/collisions_top_top.hdf5
  tests/TestData/N19/collisions_top_top.hdf5
  tests/TestData/N3/collisions_top_top.hdf5
Labels: release
